### ISSUE TITLE
Fehlerhafte Translation in der Lizenz-Liste

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/common-bundle#7]
# Problem
In der [Lizenz-Liste](https://github.com/SchulIT/common-bundle/blob/master/Resources/views/dependencies/list.html.twig) wird "Authoren" statt "Autoren" angezeigt. Da ich aber die zugehörige Translation-Datei nicht finde, kann ich leider keinen Pull Request anlegen.

### Vorher: 
<img width="802" alt="Bildschirmfoto 2022-05-05 um 11 59 38" src="https://user-images.githubusercontent.com/74987472/167246472-683f3af2-a5d1-4e1c-a613-42cfa2bfc322.png">

### Nachher:
<img width="794" alt="Bildschirmfoto 2022-05-05 um 11 59 55" src="https://user-images.githubusercontent.com/74987472/167246475-f7e90d52-d0eb-42ae-8baf-69ffe3991c20.png">

**Comment by frostieDE** [comment]
Die Datei ist in einem anderen Projekt: https://github.com/frostieDE/composer-dependency-list-bundle
